[build]
  command = "echo 'No build needed'"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.10"

[[plugins]]
  package = "@netlify/plugin-python"

[functions]
  node_bundler = "esbuild"

